site_name: CANIOT Device Documentation
repo_url: https://github.com/lucasdietrich/caniot-device.git
theme:
  name: material
nav:
  - Index: index.md
  - Nodes:
    - Garage doors controller: app-garage.md
    - Heating controller: app-heaters.md
    - Outdoor alarm controller: app-outdoor-alarm.md
    - Indoor alarm controller: app-indoor-alarm.md
    - Shutters controller: app-shutters.md
  - BSP:
    - V1: bsp-v1.md
    - Tiny: bsp-tiny.md